# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
