# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrink', '0003_auto_20170823_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='id',
        ),
        migrations.AlterField(
            model_name='urls',
            name='shrinkedURL',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
